name: Build Framework

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-14
    env:
      VERSION: 1.29.0
      THEOS: ${{ github.workspace }}/theos
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4.0"

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: ${{ github.workspace }}/theos
          submodules: recursive

      - name: Install Dependencies
        run: |
          brew install make dpkg ldid
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          release_name: SwiftProtobuf ${{env.VERSION}}
          tag_name: ${{env.VERSION}}

      - name: Build & Upload SwiftProtobuf (rootful)
        run: make package FINALPACKAGE=1
      - uses: actions/upload-release-asset@v1
        env:
          FILENAME: org.swift.protobuf.swiftprotobuf_${{env.VERSION}}_iphoneos-arm.deb
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: packages/${{env.FILENAME}}
          asset_name: ${{env.FILENAME}}
          asset_content_type: application/vnd.debian.binary-package

      - name: Build & Upload SwiftProtobuf (rootless)
        run: make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
      - uses: actions/upload-release-asset@v1
        env:
          FILENAME: org.swift.protobuf.swiftprotobuf_${{env.VERSION}}_iphoneos-arm64.deb
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: packages/${{env.FILENAME}}
          asset_name: ${{env.FILENAME}}
          asset_content_type: application/vnd.debian.binary-package
